- name: Install required packages
  apt:
    name:
      - rsnapshot
      - patch

- name: Patch rsnapshot to report rsync errors
  patch:
    src: show_rsync_errors.patch
    dest: /usr/bin/rsnapshot

- name: Ensure backupuser exists
  user: name=backuppuller generate_ssh_key=yes

- name: Install backupuser ssh config
  template:
    src: ssh_config
    dest: /home/backuppuller/.ssh/config

- name: Create /etc/rsnapshot directory
  file: path=/etc/rsnapshot state=directory

- name: Generate rsnapshot.conf files
  template:
    src: rsnapshot.conf
    dest: /etc/rsnapshot/rsnapshot-{{ item.name }}.conf
    validate: 'rsnapshot -c %s configtest'
  when: item.enabled|default(True)
  with_items: "{{ rsnapshot_backups }}"

- name: Add rsnapshot-run.sh script
  template:
    src: rsnapshot-run.sh
    dest: /etc/rsnapshot/rsnapshot-run.sh
    mode: 700

- name: Create rsnapshot cronjob (if enabled in config)
  template: src=cronjob dest=/etc/cron.d/rsnapshot-pull
  when: rsnapshot_enable_cron

- name: Remove rsnapshot cronjob (if disabled in config)
  file: path=/etc/cron.d/rsnapshot-pull state=absent
  when: not rsnapshot_enable_cron

- name: Check that ssh to hosts works
  shell: ssh -o ConnectTimeout=1 {{ item.ssh_args|default(rsnapshot_ssh_args) }} {{ item.backup_host }} test
  with_items: "{{ rsnapshot_backups }}"
  when: item.backup_host is defined and item.enabled|default(True) and testing is not defined
  changed_when: False
  ignore_errors: yes

- name: Setup logrotation
  template: src=logrotate dest=/etc/logrotate.d/rsnapshot
