- name: Install rsnapshot
  apt: name=rsnapshot state=present

- name: Ensure backupuser exists
  user: name=backuppuller generate_ssh_key=yes

- name: Create /etc/rsnapshot directory
  file: path=/etc/rsnapshot state=directory

- name: Generate rsnapshot.conf files
  template:
    src: rsnapshot.conf
    dest: /etc/rsnapshot/rsnapshot-{{ item.name }}.conf
    validate: 'rsnapshot -c %s configtest'
  with_items: "{{ rsnapshot_backups }}"

- name: Add rsnapshot-run.sh script
  template:
    src: rsnapshot-run.sh
    dest: /etc/rsnapshot/rsnapshot-run.sh
    mode: 700

- name: Create rsnapshot cronjob (if enabled in config)
  template: src=cronjob dest=/etc/cron.d/rsnapshot-pull
  when: rsnapshot_enable_cron

- name: Remove rsnapshot cronjob (if disabled in config)
  file: path=/etc/cron.d/rsnapshot-pull state=absent
  when: not rsnapshot_enable_cron

# TODO: This should only check a host once (at the moment it checks it multiple times if multiple backups are pulled from the host)
- name: Check that ssh to hosts works
  shell: ssh -o BatchMode=yes -o UserKnownHostsFile=/home/backuppuller/.ssh/known_hosts -i /home/backuppuller/.ssh/id_rsa {{ item.1.src|regex_replace('^(.*):/.*', '\1') }} test
  with_subelements:
    - "{{ rsnapshot_backups }}"
    - backup_directives
  when: item.1.src | match('.+@.+:') and item.1.type|default() != 'script' and testing is not defined
  changed_when: False
  tags: work
