- name: Install rsnapshot
  apt: name=rsnapshot state=present

- name: Ensure backupuser exists
  user: name=backuppuller generate_ssh_key=yes

- name: Create /etc/rsnapshot directory
  file: path=/etc/rsnapshot state=directory

- template:
    src: rsnapshot.conf
    dest: /etc/rsnapshot/rsnapshot-{{ item.name }}.conf
    validate: 'rsnapshot -c %s configtest'
  with_items: "{{ rsnapshot_backups }}"

- template: src=rsnapshot-run.sh dest=/etc/rsnapshot/rsnapshot-run.sh mode=700

- name: Create rsnapshot cronjob (if enabled in config)
  template: src=cronjob dest=/etc/cron.d/rsnapshot-pull
  when: rsnapshot_enable_cron

- name: Remove rsnapshot cronjob (if disabled in config)
  file: path=/etc/cron.d/rsnapshot-pull state=absent
  when: not rsnapshot_enable_cron

